from typing import Protocol


class PageStore(Protocol):
    """数据库模块只依赖稳定页接口，不依赖文件、缓存或 WAL 实现细节。"""
    def allocate_page(self)->int:...
    def release_page(self,page_id:int)->None:...
    def read_page(self,page_id:int)->bytes:...
    def write_page(self,page_id:int,payload:bytes)->int:...
    def checkpoint(self)->dict:...
    def stats(self)->dict:...
